name: Continuous Integration
on: [ pull_request, workflow_dispatch ]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    env:
      CODE_COVERAGE_THRESHOLD: 90
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
     - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
        python-version: ${{ matrix.python-version }}
     - name: Install python dependencies
       run: pip install -r app/requirements.txt
     - name: Run flask app
       run: |
         export FLASK_APP=$PWD/app/run.py
         flask run &
     - name: Run unit test
       run: coverage run -m pytest app/
     - name: Print unit test report
       run: coverage report
     - name: Validate code coverage
       run: |
         COVERAGE=$(coverage report | tail -n 1 | awk '{print $4}' | head -c 2)
         if [ "$COVERAGE" -lt "$CODE_COVERAGE_THRESHOLD" ]; then
           echo "Error: Code coverage cannot be smaller than $CODE_COVERAGE_THRESHOLD%, got $COVERAGE%"
           exit 1
         fi
  publish:
    if: "github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    needs:
      - unit_test
    env:
        IMAGE_ARTIFACT: ${{ secrets.DOCKER_HUB_USERNAME }}/sherlock:latest
    environment: production
    steps:
     - uses: actions/checkout@v2
     - name: Login to DockerHub
       run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
     - name: Build docker image
       run: docker build --tag flask-sherlock $GITHUB_WORKSPACE
     - name: Tag docker image
       run: docker tag flask-sherlock $IMAGE_ARTIFACT
     - name: Push image to DockerHub
       run: docker push $IMAGE_ARTIFACT
